on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}

      - run: pnpm install
        if: ${{ steps.release.outputs.release_created }}

      - name: Prepare is needed, because it generate types
        run: pnpm dev:prepare
        if: ${{ steps.release.outputs.release_created }}

      - name: Let's build it
        run: pnpm prepack
        if: ${{ steps.release.outputs.release_created }}

      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
